### ISSUE TITLE
[REFACTOR] iOS 3차 과제 리팩토링

### ISSUE THREAD

**Issue by Suyeon9911** [29th-WE-SOPT-iOS-Part/KimSuYeon#10]
## 📝  To-do

- [x] 코드리뷰 반영하기 -> 오토레이아웃 
- [x] 상단 UI 뷰를 Xib 로 만들어서 적용해보기 !! -> 모든 탭에서 공통적으로 사용 ! 현규슨배 코드리뷰 참고
- [ ] 코드 정리 
- [x] didset + 카테고리 선택했을 때 어두운 배경 
- [x] 도전과제 부분 피드백 + 적용해보기 
- [ ] 3차 과제 리드미 작성
