### ISSUE TITLE
[FEAT] iOS 4차 과제 Networking : 로그인 

### ISSUE THREAD

**Issue by Suyeon9911** [29th-WE-SOPT-iOS-Part/KimSuYeon#12]
## 📌  Feature Issue

로그인 뷰 실제 서버 연결 ! 

## 📝  To-do

- [x] 시작 스토리보드 변경하기 
- [x] 서버통신 1 : Encoding을 통해 swift 데이터를 JSON으로 변환
- [x] 서버통신 2 : 요청서 작성 
- [x] 서버통신 3 : 요청서를 가지고 Request 보냄
- [x] 서버통신 4 : JSON 데이터로 Response를 보내줌
- [x] 서버통신 5 : Decoding을 통해 JSON 데이터를 Swift로 변환
- [x] 서버에서 넘겨주는 message로 alert 띄우기
- [x] 로그인 성공 시 , 확인 화면으로 전환

**Comment by Suyeon9911** [comment]
아직 해결 못한거 : alert 띄울때 성공 실패 분기처리

**Comment by Suyeon9911** [comment]
+ 네비게이션 바를 Xib 로 만들어서 프로필 버튼 눌렀을 때 어떻게 로그인 화면으로 넘어가는지 모르겠음 ㅜㅜ 어디서 해줘야되는지..?

**Comment by hyun99999** [comment]
@Suyeon9911 
Xib 로 만들었으니 as 바로 들어갑니당

3가지 방법이 있을 수 있을거 같아요! 

1. delegate pattern 사용
2. NSNotification 사용
3. 뷰 컨트롤러에서 커스텀 뷰 요소 호출

> 1번은 세미나에서 다루기도 했고 1번과 2번은 아주 중요한 개념이니 한번 공부하시면서 구현해보면 좋겠네요! `*^^*`
> 막히시면 언제든지 물어보세요!

## 3. 뷰 컨트롤러에서 커스텀 뷰 요소 호출 

Xib 로 커스텀뷰를 만드는 방법은 두 가지였어요.

- View 의 Custom Class 설정
- File's Owner 의 Custom Class 설정

### 🎃 View 의 Custom Class 설정

뷰 컨트롤러에서 커스텀 뷰의 nib 객체를 가져와서 보여주기 때문에 이 부분에서 `addTarget(_:action:for:)` 를 통해서 이벤트 등록이 가능해요!

```swift
class HomeViewController: UIViewController {
    
    // MARK: - @IBOutlet Properties

    @IBOutlet weak var customNavigationBar: UIView!

    //...

    private func initNavigationBar() {
        self.navigationController?.navigationBar.isHidden = true
        // ✅ 커스텀네비게이션바 클래스에서 View 의 Custom Class 를 설정했을 떄 사용하는 코드
        guard let loadedNib = Bundle.main.loadNibNamed(String(describing: CustomNavigationBar.self), owner: self, options: nil) else { return }
        guard let navigationBar = loadedNib.first as? CustomNavigationBar else { return }
        
        navigationBar.frame = CGRect(x: 0, y: 0, width: customNavigationBar.frame.width, height: customNavigationBar.frame.height)
        customNavigationBar.addSubview(navigationBar)

        // ✅ 커스텀 뷰에서 @IBOutlet 으로 선언한 profileButton 을 가져와서 이벤트 등록.
        navigationBar.profileButton.addTarget(self, action: #selector(touchProfileButton), for: .touchUpInside)
    }

    // MARK: - @Objc Methods

    @objc
    private func touchProfileButton() {
        guard let loginVC = UIStoryboard(name: Const.Storyboard.Name.login, bundle: nil).instantiateViewController(withIdentifier: Const.ViewController.Identifier.login) as? LoginViewController else { return }
        loginVC.modalPresentationStyle = .fullScreen
        present(loginVC, animated: true, completion: nil)
    }
}
```

### 🎃 File's Owner 의 Custom Class 설정

스토리보드의 UIView class 를 CustomNavigationBar 로 설정하기 때문에 `@IBOutlet` 으로 가져와서 커스텀뷰의 요소에 `addTarget(_:action:for:)` 로 이벤트를 줄 수 있어요!

```swift
class HomeViewController: UIViewController {
    
    // MARK: - @IBOutlet Properties

    // ✅ UIView 의 class 를 CustomNavigationBar 로 설정.
    @IBOutlet weak var customNavigationBar: CustomNavigationBar!
    
    // ...

    private func initNavigationBar() {
        // ✅ CustomNavigationBar 클래스에서 File's Owner 의 Custom Class 를 설정했을 때 이벤트 등록 코드
        customNavigationBar.profileButton.addTarget(self, action: #selector(touchProfileButton), for: .touchUpInside)
    }

    // MARK: - @Objc Methods

    @objc
    private func touchProfileButton() {
        guard let loginVC = UIStoryboard(name: Const.Storyboard.Name.login, bundle: nil).instantiateViewController(withIdentifier: Const.ViewController.Identifier.login) as? LoginViewController else { return }
        loginVC.modalPresentationStyle = .fullScreen
        present(loginVC, animated: true, completion: nil)
    }
}
```

**Comment by Suyeon9911** [comment]
@hyun99999 와...이게 뭐에요슨배... 현규슨배는 증말 찐이시다.. 이말.. 오늘 참고해서 공부하면서 해봤는데 1,3번 방법은 일단 화면 전환 성공했어요 ! ~ ! !~! !~  🙋🏻‍♂️ 감솨해여 슨배.. 2번은 더 공부를.. 해보도록 하겠슴돠 ! !

**Comment by hyun99999** [comment]
나는 이렇게 만들어봤어여! 참고가 되면 좋겠네여!

```swift
// HomeViewController.swift

class HomeViewController: UIViewController {

    // ...

    private func setNotification() {
        NotificationCenter.default.addObserver(self, selector: #selector(touchProfileButton), name: NSNotification.Name(rawValue: "TouchProfileButton"), object: nil)
    }

    // MARK: - @Objc Methods

    @objc
    private func touchProfileButton() {
        guard let loginVC = UIStoryboard(name: Const.Storyboard.Name.login, bundle: nil).instantiateViewController(withIdentifier: Const.ViewController.Identifier.login) as? LoginViewController else { return }
        loginVC.modalPresentationStyle = .fullScreen
        present(loginVC, animated: true, completion: nil)
    }
}
```

```swift
//  CustomNavigationBar.swift

class CustomNavigationBar: UIView {
    
    // ...
    
    // ✅ profile button 을 터치하면 LoginViewController 로 화면전환.
    private func presentToLoginViewController() {
        NotificationCenter.default.post(name: NSNotification.Name(rawValue: "TouchProfileButton"), object: nil)
    }

    @IBAction func touchProfileButton(_ sender: Any) {
        presentToLoginViewController()
    }
}
```
