### ISSUE TITLE
[FEAT] iOS 4차 과제 Networking : 회원가입 

### ISSUE THREAD

**Issue by Suyeon9911** [29th-WE-SOPT-iOS-Part/KimSuYeon#13]
## 📌  Feature Issue

회원가입 뷰 실제 서버 연결 ! 

## 📝  To-do

- [x] 서버통신 1 : Encoding을 통해 swift 데이터를 JSON으로 변환
- [x] 서버통신 2 : 요청서 작성 
- [x] 서버통신 3 : 요청서를 가지고 Request 보냄
- [x] 서버통신 4 : JSON 데이터로 Response를 보내줌
- [x] 서버통신 5 : Decoding을 통해 JSON 데이터를 Swift로 변환
- [x] 서버에서 넘겨주는 message로 alert 띄우기 
- [x] 회원가입 성공 시 , 확인 화면으로 전환
