### ISSUE TITLE
[FEAT] iOS 7차 과제

### ISSUE THREAD

**Issue by Suyeon9911** [29th-WE-SOPT-iOS-Part/KimSuYeon#16]
## 📌  Feature Issue

데이터 연결 심화, UIGestureRecognizer 사용하기

## 📝  To-do

- [x] `imageView`에 tap gesture recognizer 달아서 action 추가 
- [x] `imageView`클릭 시 화면전환 
- [x] 이미지, 영상 타이틀, 조회 수 및 업로드 시간 데이터 전달
- [x] 버튼 클릭 시 화면 dismiss
