### ISSUE TITLE
[FEAT] iOS 2차 과제 UI 구성하기 

### ISSUE THREAD

**Issue by Suyeon9911** [29th-WE-SOPT-iOS-Part/KimSuYeon#3]
## 📌 Feature Issue

2주차 과제는 1주차 과제에서 만든 뷰에 AutoLayout을 적용시키는 것과 

Tabbar를 만든 후 확인화면에서 텝바 화면으로 이동하는 것입니다!

## 📝 To-do

▶️ UI 구성하기

- [x]  로그인 화면 AutoLayout 적용하기
- [x]  회원가입 화면 AutoLayout 적용하기
- [x]  확인 화면 AutoLayout 적용하기
- [x]  확인 화면에 "다른 계정으로 로그인하기" 버튼 추가하기
